user_pref("toolkit.cosmeticAnimations.enabled", false);
user_pref("general.smoothScroll", false);
user_pref("general.autoScroll", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.tabs.allowTabDetach", true);
user_pref("accessibility.typeaheadfind", true);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.bookmarks.openInTabClosesMenu", false);
user_pref("browser.download.autohideButton", false);
user_pref("browser.search.suggest.enabled.private", false);
user_pref("browser.startup.homepage", "https://www.google.com");
user_pref("browser.tabs.closeWindowWithLastTab", true);
user_pref("browser.tabs.insertRelatedAfterCurrent", true);
user_pref("browser.tabs.loadBookmarksInBackground", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
user_pref("browser.uidensity", 2);
user_pref("extensions.pocket.enabled", false);
user_pref("findbar.highlightAll", true);
user_pref("layout.word_select.eat_space_to_next_word", false);
//user_pref("network.proxy.autoconfig_url", "https://antizapret.prostovpn.org/proxy.pac");
user_pref("network.proxy.type", 2);

user_pref("network.http.use-cache", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk_cache_ssl", false);
user_pref("browser.cache.memory.enable", false);

user_pref("permissions.default.desktop-notification", 2);
user_pref("permissions.default.geo", 2);
user_pref("permissions.default.camera", 2);
user_pref("permissions.default.microphone", 2);
user_pref("permissions.default.xr", 2);
user_pref("media.autoplay.default", 1);
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("toolkit.telemetry.server", "");
user_pref("browser.newtabpage.activity-stream.telemetry.structuredIngestion.endpoint", "");
user_pref("toolkit.telemetry.cachedClientID", "");
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("media.navigator.enabled", false);
user_pref("media.peerconnection.enabled", false);
user_pref("network.security.esni.enabled", true);
user_pref("network.trr.mode", 3);
// https://dns.google/dns-query
// https://dns.adguard.com/dns-query
// https://cloudflare-dns.com/dns-query
// https://github.com/curl/curl/wiki/DNS-over-HTTPS
user_pref("network.trr.uri", "https://cloudflare-dns.com/dns-query");
